development:
  yelp_consumer_key:    'iTwjw0DOU1LbsxYVY-xBMQ'
  yelp_consumer_secret: 'PzGWGnWa0gOv3YSSLQeeE8yv2F0'
  yelp_token:           'JMwkWcdZ-fviGUCQZKfmwGovIm55sUtW'
  yelp_token_secret:    '9wot6yuKA9jfYGKdR3L-3cDpCO0'
  google_key:           'AIzaSyCvkcahP3aIjobWeYXxanodRw9KlSXfUxg'
